config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'homes_about'
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end



  resources :groups, only: [:new, :create, :edit, :update, :index, :show] do
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
    member do
      post :join
      delete :leave
    end

  end

  get 'search' => "search#search"

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
 
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def self.looks(search, word)
                if search == "forward_match"
                    Book.where("title LIKE?","#{word}%")
                elsif search == "backward_match"
                    Book.where("title LIKE?","%#{word}")
                elsif search == "perfect_match"
                    Book.where(title: word)
                elsif search == "partial_match"
                    Book.where("title LIKE?","%#{word}%")
                else
                        Book.all
                end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :group
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :events, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  attachment :group_image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false
  


  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower


  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed

  has_many :group_users
  has_many :groups, through: :group_users

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

 	def self.looks(search, word)
    if search == "forward_match"
                        User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
                        User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
                       User.where(name: word)
    elsif search == "partial_match"
                        User.where("name LIKE?","%#{word}%")
    else
                        User.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = current_user
    @user_new = @book.user
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      @books = Book.all
      render "index"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update, :show]

  def index
    @groups = Group.all
    @book = Book.new
  end

  def show
    @book = Book.new
  end

  def new
    @group = Group.new
    @group.users << current_user

  end

  def create
    @group = Group.new(group_params)
    @group.users << current_user
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  def edit
    if @group.owner_id.to_i == current_user.id.to_i
      render "edit"
    else
      redirect_to groups_path
    end
  end

  def join
    @group = Group.find_by(id: params[:id])
    if !@group.users.include?(current_user)
        @group.users << current_user
        redirect_to groups_path
    end
  end

  def leave
    @group = Group.find_by(id: params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @title = params[:title]
    @content = params[:content]
    SampleMailer.send_when_update(group_users, @title, @content).deliver
  end


  private
  def group_params
    params.require(:group).permit(:name, :introduction, :group_image, :owner_id, user_ids: [] )
  end

  def set_group
    @group = Group.find(params[:id])
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/finders_helper.rb
module FindersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_for group do |f| %>
    <% if group.errors.any? %>

      <div class="chat-group-form__errors">
        <h2><%= "#{group.errors.full_messages.count}件のエラーが発生しました。" %></h2>
        <ul>
          <% group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>

    <% else %>

    <div class="chat-group-form__field">
      <div class="chat-group-form__field--left">
        <%= f.label :name, "グループ名", class: 'chat-group-form__label' %>
      </div>
      <div class="chat-group-form__field--right">
        <%= f.text_field :name, class: 'chat__group_name chat-group-form__input' %>
      </div>
    </div>

    <div class="chat-group-form__field.clearfix">
      この部分はインクリメンタルサーチ（ユーザー追加の非同期化)のときに使用します
    </div>

    <div>
      <div>
        <%= f.label :introductin, "紹介文" %>
      </div>
      <div>
        <%= f.text_area :introduction %>
      </div>
    </div>

     <div>
      <div>
        <%= f.label :group_image, "グループ画像" %>
      </div>
      <div>
        <%= f.attachment_field :group_image %>

      </div>
    </div>




        <%= f.submit class: 'btn btn-info' %>

    </div>
  <% end %>
<% end %>

app/views/groups/edit.html.erb
<div class="container">
  <h1>チャットグループ編集</h1>
  <%= render partial: 'groups/form', locals: { group: @group } %>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>


    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>


    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
        <table class='table'>
          <thead>
            <tr>
              <th></th>
              <th>グループ名</th>
              <th>紹介文</th>
              <th>メンバー数</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @groups.each do |group| %>
            <tr>
              <td><%= attachment_image_tag(group, :group_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
              <td><%= link_to "#{group.name}", group_path(group) %></td>
              <td><%= group.introduction %></td>
              <td><%= group.users.count %></td>
              <% if group.owner_id.to_i == current_user.id.to_i %>
              <td><%= link_to "Edit", edit_group_path(group), class: "btn btn-success" %></td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <h1>Create Group</h1>
  <%= render partial: 'groups/form', locals: { group: @group } %>

</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Event Mail</h3>
        <%= form_with url: group_send_mail_path(@group), method: :get, local:true do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control book_title' %>
          </div>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control book_body' %>
          </div>
          <div class="form-group text-right">
            <%= f.submit "送信", class: 'btn btn-success' %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="">
  <h3 class="margin_top text-center">送信が完了しました</h3>
  <div class="main_width">
  <div class="margin_top">内容は以下の通りです。</div>
    <div class="small_margin_top">
      [タイトル]<p class="font-weight-bold"> <%= @title %></p>
    </div>
    <div>
      [本文]<p class="font-weight-bold"> <%= safe_join(@content.split("\n"),tag(:br)) %></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>


    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>


    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
        <table class='table'>
          <thead>
            <tr>
              <th></th>
              <th>グループ名</th>
              <th>紹介文</th>
              <th>メンバー</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= attachment_image_tag(@group, :group_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
              <td><%= link_to "#{@group.name}", group_path(@group) %></td>
              <td><%= @group.introduction %></td>
              <td><% @group.group_users.each do |f| %>
                    <%= f.user.name %>
                  <% end %>
              </td>
              <% if @group.owner_id.to_i != current_user.id.to_i %>
                <% unless GroupUser.exists?(group_id: @group.id, user_id: current_user.id) %>
                <td><%= link_to "Join this group", join_group_path(@group), class: "btn btn-success", method: :post %></td>
                <% else %>
                <td><%= link_to "Leave this group", leave_group_path(@group), class: "btn btn-danger", method: :delete %></td>
                <% end %>
              <% end %>
              <% if @group.owner_id.to_i == current_user.id.to_i %>
                <td><%= link_to "Edit", edit_group_path(@group), class: "btn btn-success" %></td>
                <td><%= link_to "Notice an Event", group_new_mail_path(@group), class: "btn btn-info" %></td>
              <% end %>
            </tr>

          </tbody>
        </table>
    </div>
  </div>
</div>